### ISSUE TITLE
Be more clever about live updating fastFT

### ISSUE THREAD

**Issue by charypar** [Financial-Times/next-front-page#158]
The current fastFT polling from the browser is putting an unnecessary strain on the network stack and there are much better ways of doing live updates than dumb polling.

This is to track ideas and suggestions around how to do fastFT properly.

**Comment by adambraimbridge** [comment]
It's pie in the sky thinking, but in the long run, a live-update solution would be useful for all pages, not just fastFT. I'm thinking live blogs, live Q&A, stream pages, and even 'normal' posts on the front page. 

By the way, http://ftalphaville.ft.com/ streams posts (on create/update/delete) via Pusher (which is rediculously costly, but not a dealbreaker because it's a fraction of the traffic of the ft.com homepage).

**Comment by adambraimbridge** [comment]
![image](https://cloud.githubusercontent.com/assets/224547/9082894/033ef696-3b5f-11e5-8a9d-1ef550c82da3.png)

**Comment by charypar** [comment]
So what if we did SSE and only polled as a fallback with some clever way to skip unnecessary polls when the user is not looking...?

**Comment by adgad** [comment]
We're not live updating fastFT anymore - can refer to this if that functionality ever comes back.
