### ISSUE TITLE
Font size in footer is too big

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/next-front-page#189]

**Comment by imranolas** [comment]
<img width="624" alt="screen shot 2015-08-12 at 13 14 37" src="https://cloud.githubusercontent.com/assets/4206028/9223662/0d0b277c-40f4-11e5-8173-01cb632299ad.png">

**Comment by charypar** [comment]
I'll fix this as part of #186...

**Comment by charypar** [comment]
Actually @wheresrhys, I think this might need fixing in the component, it's the front-page default styling affecting it, because the component doesn't set it's `font-size` and `text-decoration`. Even if I turn all those rules off, the component doesn't look like it does on the stream page, so I'm guessing it's relying on some global rules there too?

Do you want a PR?

**Comment by wheresrhys** [comment]
Yes please

-- 

------------------------------
This email was sent by a company owned by Pearson plc, registered office at 
80 Strand, London WC2R 0RL.  Registered in England and Wales with company 
number 53723.
