### ISSUE TITLE
Treatment of fastFT on mobile

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/next-front-page#46]
I think there are two problems with shrinking fastFT down to just the heading on mobile

1. It ends up looking like a heading for the top stories
1. Part of the point of fastft is that it should be available at a glance - by showing no headlines at all on mobile it loses this

**Comment by matthew-andrews** [comment]
might be better to discuss this with badgers ux, dev, design & mark a in person/on slack rather than in a github issue…

**Comment by wheresrhys** [comment]
I thought here was the agreed place for feedback?

**Comment by matthew-andrews** [comment]
i missed that memo……?

**Comment by charypar** [comment]
In this case of a larger UX feedback, it's better to do it in person with us. We have a different treatment for mobile fastFT planned, this was just for the MVP, but based on feedback from Robert we're doing the original idea even for MVP, because, as you say, the current one looks like a section headline.

We should have some prints of the mobile/tablet treatment on our board, it's essentially a tab control.
